const hotCity = [
  {
    'regionId': '110100',
    'name': '北京'
  },
  {
    'regionId': '310100',
    'name': '上海'
  },
  {
    'regionId': '440100',
    'name': '广州'
  },
  {
    'regionId': '440300',
    'name': '深圳'
  },
  {
    'regionId': '120100',
    'name': '天津'
  },
  {
    'regionId': '500100',
    'name': '重庆'
  },
  {
    'regionId': '330100',
    'name': '杭州'
  },
  {
    'regionId': '320100',
    'name': '南京'
  },
  {
    'regionId': '370100',
    'name': '济南'
  },
  {
    'regionId': '420100',
    'name': '武汉'
  },
  {
    'regionId': '430100',
    'name': '长沙'
  },
  {
    'regionId': '510100',
    'name': '成都'
  }
]
const citys = [
  {
    'A': [{
      'regionId': '513200',
      'name': '阿坝',
      'firstSpell': 'A',
      'shortSpell': 'AB',
      'spell': 'ABa'
    }, {
      'regionId': '610900',
      'name': '安康',
      'firstSpell': 'A',
      'shortSpell': 'AK',
      'spell': 'AnKang'
    }, {
      'regionId': '652900',
      'name': '阿克苏',
      'firstSpell': 'A',
      'shortSpell': 'AKS',
      'spell': 'AKeSu'
    }, {
      'regionId': '542500',
      'name': '阿里',
      'firstSpell': 'A',
      'shortSpell': 'AL',
      'spell': 'ALi'
    }, {
      'regionId': '659002',
      'name': '阿拉尔',
      'firstSpell': 'A',
      'shortSpell': 'ALE',
      'spell': 'ALaEr'
    }, {
      'regionId': '152900',
      'name': '阿拉善',
      'firstSpell': 'A',
      'shortSpell': 'ALSM',
      'spell': 'ALaShanMeng'
    }, {
      'regionId': '654300',
      'name': '阿勒泰',
      'firstSpell': 'A',
      'shortSpell': 'ALT',
      'spell': 'ALeTai'
    }, {
      'regionId': '340800',
      'name': '安庆',
      'firstSpell': 'A',
      'shortSpell': 'AQ',
      'spell': 'AnQing'
    }, {
      'regionId': '210300',
      'name': '鞍山',
      'firstSpell': 'A',
      'shortSpell': 'AS',
      'spell': 'AnShan'
    }, {
      'regionId': '520400',
      'name': '安顺',
      'firstSpell': 'A',
      'shortSpell': 'AS',
      'spell': 'AnShun'
    }, {
      'regionId': '410500',
      'name': '安阳',
      'firstSpell': 'A',
      'shortSpell': 'AY',
      'spell': 'AnYang'
    }],
    'B': [{
      'regionId': '110100',
      'name': '北京',
      'firstSpell': 'B',
      'shortSpell': 'BJ',
      'spell': 'BeiJing'
    }, {
      'regionId': '340300',
      'name': '蚌埠',
      'firstSpell': 'B',
      'shortSpell': 'BB',
      'spell': 'BengBu'
    }, {
      'regionId': '220800',
      'name': '白城',
      'firstSpell': 'B',
      'shortSpell': 'BC',
      'spell': 'BaiCheng'
    }, {
      'regionId': '130600',
      'name': '保定',
      'firstSpell': 'B',
      'shortSpell': 'BD',
      'spell': 'BaoDing'
    }, {
      'regionId': '652700',
      'name': '博尔塔拉',
      'firstSpell': 'B',
      'shortSpell': 'BETL',
      'spell': 'BoErTaLa'
    }, {
      'regionId': '450500',
      'name': '北海',
      'firstSpell': 'B',
      'shortSpell': 'BH',
      'spell': 'BeiHai'
    }, {
      'regionId': '520500',
      'name': '毕节',
      'firstSpell': 'B',
      'shortSpell': 'BJ',
      'spell': 'BiJie'
    }, {
      'regionId': '610300',
      'name': '宝鸡',
      'firstSpell': 'B',
      'shortSpell': 'BJ',
      'spell': 'BaoJi'
    }, {
      'regionId': '220600',
      'name': '白山',
      'firstSpell': 'B',
      'shortSpell': 'BS',
      'spell': 'BaiShan'
    }, {
      'regionId': '451000',
      'name': '百色',
      'firstSpell': 'B',
      'shortSpell': 'BS',
      'spell': 'BaiSe'
    }, {
      'regionId': '530500',
      'name': '保山',
      'firstSpell': 'B',
      'shortSpell': 'BS',
      'spell': 'BaoShan'
    }, {
      'regionId': '150200',
      'name': '包头',
      'firstSpell': 'B',
      'shortSpell': 'BT',
      'spell': 'BaoTou'
    }, {
      'regionId': '210500',
      'name': '本溪',
      'firstSpell': 'B',
      'shortSpell': 'BX',
      'spell': 'BenXi'
    }, {
      'regionId': '620400',
      'name': '白银',
      'firstSpell': 'B',
      'shortSpell': 'BY',
      'spell': 'BaiYin'
    }, {
      'regionId': '652800',
      'name': '巴音郭楞',
      'firstSpell': 'B',
      'shortSpell': 'BYGL',
      'spell': 'BaYinGuoLeng'
    }, {
      'regionId': '150800',
      'name': '巴彦淖尔',
      'firstSpell': 'B',
      'shortSpell': 'BYNE',
      'spell': 'BaYanNaoEr'
    }, {
      'regionId': '341600',
      'name': '亳州',
      'firstSpell': 'B',
      'shortSpell': 'BZ',
      'spell': 'BoZhou'
    }, {
      'regionId': '371600',
      'name': '滨州',
      'firstSpell': 'B',
      'shortSpell': 'BZ',
      'spell': 'BinZhou'
    }, {
      'regionId': '511900',
      'name': '巴中',
      'firstSpell': 'B',
      'shortSpell': 'BZ',
      'spell': 'BaZhong'
    }],
    'C': [{
      'regionId': '500100',
      'name': '重庆',
      'firstSpell': 'C',
      'shortSpell': 'CQ',
      'spell': 'ChongQing'
    }, {
      'regionId': '220100',
      'name': '长春',
      'firstSpell': 'C',
      'shortSpell': 'CC',
      'spell': 'ChangChun'
    }, {
      'regionId': '510100',
      'name': '成都',
      'firstSpell': 'C',
      'shortSpell': 'CD',
      'spell': 'ChengDu'
    }, {
      'regionId': '430100',
      'name': '长沙',
      'firstSpell': 'C',
      'shortSpell': 'CS',
      'spell': 'ChangSha'
    }, {
      'regionId': '130800',
      'name': '承德',
      'firstSpell': 'C',
      'shortSpell': 'CD',
      'spell': 'ChengDe'
    }, {
      'regionId': '430700',
      'name': '常德',
      'firstSpell': 'C',
      'shortSpell': 'CD',
      'spell': 'ChangDe'
    }, {
      'regionId': '542100',
      'name': '昌都',
      'firstSpell': 'C',
      'shortSpell': 'CD',
      'spell': 'ChangDu'
    }, {
      'regionId': '150400',
      'name': '赤峰',
      'firstSpell': 'C',
      'shortSpell': 'CF',
      'spell': 'ChiFeng'
    }, {
      'regionId': '652300',
      'name': '昌吉',
      'firstSpell': 'C',
      'shortSpell': 'CJ',
      'spell': 'ChangTi'
    }, {
      'regionId': '532300',
      'name': '楚雄',
      'firstSpell': 'C',
      'shortSpell': 'CX',
      'spell': 'ChuXiong'
    }, {
      'regionId': '211300',
      'name': '朝阳',
      'firstSpell': 'C',
      'shortSpell': 'CY',
      'spell': 'ChaoYang'
    }, {
      'regionId': '130900',
      'name': '沧州',
      'firstSpell': 'C',
      'shortSpell': 'CZ',
      'spell': 'CangZhou'
    }, {
      'regionId': '140400',
      'name': '长治',
      'firstSpell': 'C',
      'shortSpell': 'CZ',
      'spell': 'ChangZhi'
    }, {
      'regionId': '320400',
      'name': '常州',
      'firstSpell': 'C',
      'shortSpell': 'CZ',
      'spell': 'ChangZhou'
    }, {
      'regionId': '340181',
      'name': '巢湖',
      'firstSpell': 'C',
      'shortSpell': 'CH',
      'spell': 'ChaoHu'
    }, {
      'regionId': '341100',
      'name': '滁州',
      'firstSpell': 'C',
      'shortSpell': 'CZ',
      'spell': 'ChuZhou'
    }, {
      'regionId': '341700',
      'name': '池州',
      'firstSpell': 'C',
      'shortSpell': 'CZ',
      'spell': 'ChiZhou'
    }, {
      'regionId': '431000',
      'name': '郴州',
      'firstSpell': 'C',
      'shortSpell': 'CZ',
      'spell': 'ChenZhou'
    }, {
      'regionId': '445100',
      'name': '潮州',
      'firstSpell': 'C',
      'shortSpell': 'CZ',
      'spell': 'ChaoZhou'
    }, {
      'regionId': '451400',
      'name': '崇左',
      'firstSpell': 'C',
      'shortSpell': 'CZ',
      'spell': 'ChongZuo'
    }],
    'D': [{
      'regionId': '210200',
      'name': '大连',
      'firstSpell': 'D',
      'shortSpell': 'DL',
      'spell': 'DaLian'
    }, {
      'regionId': '210600',
      'name': '丹东',
      'firstSpell': 'D',
      'shortSpell': 'DD',
      'spell': 'DanDong'
    }, {
      'regionId': '469007',
      'name': '东方',
      'firstSpell': 'D',
      'shortSpell': 'DF',
      'spell': 'DongFang'
    }, {
      'regionId': '441900',
      'name': '东莞',
      'firstSpell': 'D',
      'shortSpell': 'DG',
      'spell': 'DongGuan'
    }, {
      'regionId': '533100',
      'name': '德宏',
      'firstSpell': 'D',
      'shortSpell': 'DH',
      'spell': 'DeHong'
    }, {
      'regionId': '532900',
      'name': '大理',
      'firstSpell': 'D',
      'shortSpell': 'DL',
      'spell': 'DaLi'
    }, {
      'regionId': '230600',
      'name': '大庆',
      'firstSpell': 'D',
      'shortSpell': 'DQ',
      'spell': 'DaQing'
    }, {
      'regionId': '533400',
      'name': '迪庆',
      'firstSpell': 'D',
      'shortSpell': 'DQ',
      'spell': 'DiQing'
    }, {
      'regionId': '140200',
      'name': '大同',
      'firstSpell': 'D',
      'shortSpell': 'DT',
      'spell': 'DaTong'
    }, {
      'regionId': '621100',
      'name': '定西',
      'firstSpell': 'D',
      'shortSpell': 'DX',
      'spell': 'DingXi'
    }, {
      'regionId': '232700',
      'name': '大兴安岭',
      'firstSpell': 'D',
      'shortSpell': 'DXAL',
      'spell': 'DaXingAnLing'
    }, {
      'regionId': '370500',
      'name': '东营',
      'firstSpell': 'D',
      'shortSpell': 'DY',
      'spell': 'DongYing'
    }, {
      'regionId': '510600',
      'name': '德阳',
      'firstSpell': 'D',
      'shortSpell': 'DY',
      'spell': 'DeYang'
    }, {
      'regionId': '371400',
      'name': '德州',
      'firstSpell': 'D',
      'shortSpell': 'DZ',
      'spell': 'DeZhou'
    }, {
      'regionId': '469003',
      'name': '儋州',
      'firstSpell': 'D',
      'shortSpell': 'DZ',
      'spell': 'DanZhou'
    }, {
      'regionId': '511700',
      'name': '达州',
      'firstSpell': 'D',
      'shortSpell': 'DZ',
      'spell': 'DaZhou'
    }],
    'E': [{
      'regionId': '150600',
      'name': '鄂尔多斯',
      'firstSpell': 'E',
      'shortSpell': 'EEDS',
      'spell': 'EErDuoSi'
    }, {
      'regionId': '422800',
      'name': '恩施',
      'firstSpell': 'E',
      'shortSpell': 'ES',
      'spell': 'EnShi'
    }, {
      'regionId': '420700',
      'name': '鄂州',
      'firstSpell': 'E',
      'shortSpell': 'EZ',
      'spell': 'EZhou'
    }],
    'F': [{
      'regionId': '350100',
      'name': '福州',
      'firstSpell': 'F',
      'shortSpell': 'FZ',
      'spell': 'FuZhou'
    }, {
      'regionId': '450600',
      'name': '防城港',
      'firstSpell': 'F',
      'shortSpell': 'FCG',
      'spell': 'FangChengGang'
    }, {
      'regionId': '210400',
      'name': '抚顺',
      'firstSpell': 'F',
      'shortSpell': 'FS',
      'spell': 'FuShun'
    }, {
      'regionId': '440600',
      'name': '佛山',
      'firstSpell': 'F',
      'shortSpell': 'FS',
      'spell': 'FoShan'
    }, {
      'regionId': '210900',
      'name': '阜新',
      'firstSpell': 'F',
      'shortSpell': 'FX',
      'spell': 'FuXin'
    }, {
      'regionId': '341200',
      'name': '阜阳',
      'firstSpell': 'F',
      'shortSpell': 'FY',
      'spell': 'FuYang'
    }, {
      'regionId': '361000',
      'name': '抚州',
      'firstSpell': 'F',
      'shortSpell': 'FZ',
      'spell': 'FuZhou'
    }],
    'G': [{
      'regionId': '520100',
      'name': '贵阳',
      'firstSpell': 'G',
      'shortSpell': 'GY',
      'spell': 'GuiYang'
    }, {
      'regionId': '440100',
      'name': '广州',
      'firstSpell': 'G',
      'shortSpell': 'GZ',
      'spell': 'GuangZhou'
    }, {
      'regionId': '511600',
      'name': '广安',
      'firstSpell': 'G',
      'shortSpell': 'GA',
      'spell': 'GuangAn'
    }, {
      'regionId': '450800',
      'name': '贵港',
      'firstSpell': 'G',
      'shortSpell': 'GG',
      'spell': 'GuiGang'
    }, {
      'regionId': '450300',
      'name': '桂林',
      'firstSpell': 'G',
      'shortSpell': 'GL',
      'spell': 'GuiLin'
    }, {
      'regionId': '632600',
      'name': '果洛',
      'firstSpell': 'G',
      'shortSpell': 'GL',
      'spell': 'GuoLuo'
    }, {
      'regionId': '623000',
      'name': '甘南',
      'firstSpell': 'G',
      'shortSpell': 'GN',
      'spell': 'GanNan'
    }, {
      'regionId': '510800',
      'name': '广元',
      'firstSpell': 'G',
      'shortSpell': 'GY',
      'spell': 'GuangYuan'
    }, {
      'regionId': '640400',
      'name': '固原',
      'firstSpell': 'G',
      'shortSpell': 'GY',
      'spell': 'GuYuan'
    }, {
      'regionId': '360700',
      'name': '赣州',
      'firstSpell': 'G',
      'shortSpell': 'GZ',
      'spell': 'GanZhou'
    }, {
      'regionId': '513300',
      'name': '甘孜',
      'firstSpell': 'G',
      'shortSpell': 'GZ',
      'spell': 'GanZi'
    }],
    'H': [{
      'regionId': '230100',
      'name': '哈尔滨',
      'firstSpell': 'H',
      'shortSpell': 'HEB',
      'spell': 'HaErBin'
    }, {
      'regionId': '340100',
      'name': '合肥',
      'firstSpell': 'H',
      'shortSpell': 'HF',
      'spell': 'HeFei'
    }, {
      'regionId': '150100',
      'name': '呼和浩特',
      'firstSpell': 'H',
      'shortSpell': 'HHHT',
      'spell': 'HuHeHaoTe'
    }, {
      'regionId': '460100',
      'name': '海口',
      'firstSpell': 'H',
      'shortSpell': 'HK',
      'spell': 'HaiKou'
    }, {
      'regionId': '330100',
      'name': '杭州',
      'firstSpell': 'H',
      'shortSpell': 'HZ',
      'spell': 'HangZhou'
    }, {
      'regionId': '320800',
      'name': '淮安',
      'firstSpell': 'H',
      'shortSpell': 'HA',
      'spell': 'HuaiAn'
    }, {
      'regionId': '340600',
      'name': '淮北',
      'firstSpell': 'H',
      'shortSpell': 'HB',
      'spell': 'HuaiBei'
    }, {
      'regionId': '410600',
      'name': '鹤壁',
      'firstSpell': 'H',
      'shortSpell': 'HB',
      'spell': 'HeBi'
    }, {
      'regionId': '632200',
      'name': '海北',
      'firstSpell': 'H',
      'shortSpell': 'HB',
      'spell': 'HaiBei'
    }, {
      'regionId': '451200',
      'name': '河池',
      'firstSpell': 'H',
      'shortSpell': 'HC',
      'spell': 'HeChi'
    }, {
      'regionId': '130400',
      'name': '邯郸',
      'firstSpell': 'H',
      'shortSpell': 'HD',
      'spell': 'HanDan'
    }, {
      'regionId': '630200',
      'name': '海东',
      'firstSpell': 'H',
      'shortSpell': 'HD',
      'spell': 'HaiDong'
    }, {
      'regionId': '230400',
      'name': '鹤岗',
      'firstSpell': 'H',
      'shortSpell': 'HG',
      'spell': 'HeGang'
    }, {
      'regionId': '421100',
      'name': '黄冈',
      'firstSpell': 'H',
      'shortSpell': 'HG',
      'spell': 'HuangGang'
    }, {
      'regionId': '231100',
      'name': '黑河',
      'firstSpell': 'H',
      'shortSpell': 'HH',
      'spell': 'HeiHe'
    }, {
      'regionId': '431200',
      'name': '怀化',
      'firstSpell': 'H',
      'shortSpell': 'HH',
      'spell': 'HuaiHua'
    }, {
      'regionId': '532500',
      'name': '红河',
      'firstSpell': 'H',
      'shortSpell': 'HH',
      'spell': 'HongHe'
    }, {
      'regionId': '150700',
      'name': '呼伦贝尔',
      'firstSpell': 'H',
      'shortSpell': 'HLBE',
      'spell': 'HuLunBeiEr'
    }, {
      'regionId': '211400',
      'name': '葫芦岛',
      'firstSpell': 'H',
      'shortSpell': 'HLD',
      'spell': 'HuLuDao'
    }, {
      'regionId': '652200',
      'name': '哈密',
      'firstSpell': 'H',
      'shortSpell': 'HM',
      'spell': 'HaMi'
    }, {
      'regionId': '340400',
      'name': '淮南',
      'firstSpell': 'H',
      'shortSpell': 'HN',
      'spell': 'HuaiNan'
    }, {
      'regionId': '632300',
      'name': '黄南',
      'firstSpell': 'H',
      'shortSpell': 'HN',
      'spell': 'HuangNan'
    }, {
      'regionId': '632500',
      'name': '海南',
      'firstSpell': 'H',
      'shortSpell': 'HN',
      'spell': 'HaiNan'
    }, {
      'regionId': '131100',
      'name': '衡水',
      'firstSpell': 'H',
      'shortSpell': 'HS',
      'spell': 'HengShui'
    }, {
      'regionId': '341000',
      'name': '黄山',
      'firstSpell': 'H',
      'shortSpell': 'HS',
      'spell': 'HuangShang'
    }, {
      'regionId': '420200',
      'name': '黄石',
      'firstSpell': 'H',
      'shortSpell': 'HS',
      'spell': 'HuangShi'
    }, {
      'regionId': '653200',
      'name': '和田',
      'firstSpell': 'H',
      'shortSpell': 'HT',
      'spell': 'HeTian'
    }, {
      'regionId': '632800',
      'name': '海西蒙',
      'firstSpell': 'H',
      'shortSpell': 'HXM',
      'spell': 'HaiXiMeng'
    }, {
      'regionId': '430400',
      'name': '衡阳',
      'firstSpell': 'H',
      'shortSpell': 'HY',
      'spell': 'HengYang'
    }, {
      'regionId': '441600',
      'name': '河源',
      'firstSpell': 'H',
      'shortSpell': 'HY',
      'spell': 'HeYuan'
    }, {
      'regionId': '330500',
      'name': '湖州',
      'firstSpell': 'H',
      'shortSpell': 'HZ',
      'spell': 'HuZhou'
    }, {
      'regionId': '371700',
      'name': '菏泽',
      'firstSpell': 'H',
      'shortSpell': 'HZ',
      'spell': 'HeZe'
    }, {
      'regionId': '441300',
      'name': '惠州',
      'firstSpell': 'H',
      'shortSpell': 'HZ',
      'spell': 'HuiZhou'
    }, {
      'regionId': '451100',
      'name': '贺州',
      'firstSpell': 'H',
      'shortSpell': 'HZ',
      'spell': 'HeZhou'
    }, {
      'regionId': '610700',
      'name': '汉中',
      'firstSpell': 'H',
      'shortSpell': 'HZ',
      'spell': 'HanZhong'
    }],
    'J': [{
      'regionId': '370100',
      'name': '济南',
      'firstSpell': 'J',
      'shortSpell': 'JN',
      'spell': 'JiNan'
    }, {
      'regionId': '360800',
      'name': '吉安',
      'firstSpell': 'J',
      'shortSpell': 'JA',
      'spell': 'JiAn'
    }, {
      'regionId': '140500',
      'name': '晋城',
      'firstSpell': 'J',
      'shortSpell': 'JC',
      'spell': 'JinCheng'
    }, {
      'regionId': '620300',
      'name': '金昌',
      'firstSpell': 'J',
      'shortSpell': 'JC',
      'spell': 'JinChang'
    }, {
      'regionId': '360200',
      'name': '景德镇',
      'firstSpell': 'J',
      'shortSpell': 'JDZ',
      'spell': 'JingDeZhen'
    }, {
      'regionId': '330700',
      'name': '金华',
      'firstSpell': 'J',
      'shortSpell': 'JH',
      'spell': 'JinHua'
    }, {
      'regionId': '360400',
      'name': '九江',
      'firstSpell': 'J',
      'shortSpell': 'JJ',
      'spell': 'JiuJiang'
    }, {
      'regionId': '220200',
      'name': '吉林',
      'firstSpell': 'J',
      'shortSpell': 'JL',
      'spell': 'JiLin'
    }, {
      'regionId': '420800',
      'name': '荆门',
      'firstSpell': 'J',
      'shortSpell': 'JM',
      'spell': 'JingMen'
    }, {
      'regionId': '440700',
      'name': '江门',
      'firstSpell': 'J',
      'shortSpell': 'JM',
      'spell': 'JiangMen'
    }, {
      'regionId': '230800',
      'name': '佳木斯',
      'firstSpell': 'J',
      'shortSpell': 'JMS',
      'spell': 'JiaMuSi'
    }, {
      'regionId': '370800',
      'name': '济宁',
      'firstSpell': 'J',
      'shortSpell': 'JN',
      'spell': 'JiNing'
    }, {
      'regionId': '620900',
      'name': '酒泉',
      'firstSpell': 'J',
      'shortSpell': 'JQ',
      'spell': 'JiuQuan'
    }, {
      'regionId': '230300',
      'name': '鸡西',
      'firstSpell': 'J',
      'shortSpell': 'JX',
      'spell': 'JiXi'
    }, {
      'regionId': '330400',
      'name': '嘉兴',
      'firstSpell': 'J',
      'shortSpell': 'JX',
      'spell': 'JiaXing'
    }, {
      'regionId': '419001',
      'name': '济源',
      'firstSpell': 'J',
      'shortSpell': 'JY',
      'spell': 'JiYuan'
    }, {
      'regionId': '445200',
      'name': '揭阳',
      'firstSpell': 'J',
      'shortSpell': 'JY',
      'spell': 'JieYang'
    }, {
      'regionId': '620200',
      'name': '嘉峪关',
      'firstSpell': 'J',
      'shortSpell': 'JYG',
      'spell': 'JiaYuGuan'
    }, {
      'regionId': '140700',
      'name': '晋中',
      'firstSpell': 'J',
      'shortSpell': 'JZ',
      'spell': 'JinZhong'
    }, {
      'regionId': '210700',
      'name': '锦州',
      'firstSpell': 'J',
      'shortSpell': 'JZ',
      'spell': 'JinZhou'
    }, {
      'regionId': '410800',
      'name': '焦作',
      'firstSpell': 'J',
      'shortSpell': 'JZ',
      'spell': 'JiaoZuo'
    }, {
      'regionId': '421000',
      'name': '荆州',
      'firstSpell': 'J',
      'shortSpell': 'JZ',
      'spell': 'JingZhou'
    }],
    'K': [{
      'regionId': '530100',
      'name': '昆明',
      'firstSpell': 'K',
      'shortSpell': 'KM',
      'spell': 'KunMing'
    }, {
      'regionId': '410200',
      'name': '开封',
      'firstSpell': 'K',
      'shortSpell': 'KF',
      'spell': 'KaiFeng'
    }, {
      'regionId': '650200',
      'name': '克拉玛依',
      'firstSpell': 'K',
      'shortSpell': 'KLMY',
      'spell': 'KeLaMaYi'
    }, {
      'regionId': '653100',
      'name': '喀什',
      'firstSpell': 'K',
      'shortSpell': 'KS',
      'spell': 'KaShi'
    }, {
      'regionId': '654003',
      'name': '奎屯市',
      'firstSpell': 'K',
      'shortSpell': 'KT',
      'spell': 'KuiTun'
    }, {
      'regionId': '653000',
      'name': '克孜勒苏',
      'firstSpell': 'K',
      'shortSpell': 'KZLS',
      'spell': 'KeZiLeSu'
    }],
    'L': [{
      'regionId': '540100',
      'name': '拉萨',
      'firstSpell': 'L',
      'shortSpell': 'LS',
      'spell': 'LaSa'
    }, {
      'regionId': '620100',
      'name': '兰州',
      'firstSpell': 'L',
      'shortSpell': 'LZ',
      'spell': 'LanZhou'
    }, {
      'regionId': '341500',
      'name': '六安',
      'firstSpell': 'L',
      'shortSpell': 'LA',
      'spell': 'LiuAn'
    }, {
      'regionId': '451300',
      'name': '来宾',
      'firstSpell': 'L',
      'shortSpell': 'LB',
      'spell': 'LaiBin'
    }, {
      'regionId': '371500',
      'name': '聊城',
      'firstSpell': 'L',
      'shortSpell': 'LC',
      'spell': 'LiaoCheng'
    }, {
      'regionId': '530900',
      'name': '临沧',
      'firstSpell': 'L',
      'shortSpell': 'LC',
      'spell': 'LinCang'
    }, {
      'regionId': '431300',
      'name': '娄底',
      'firstSpell': 'L',
      'shortSpell': 'LD',
      'spell': 'LouDi'
    }, {
      'regionId': '131000',
      'name': '廊坊',
      'firstSpell': 'L',
      'shortSpell': 'LF',
      'spell': 'LangFang'
    }, {
      'regionId': '141000',
      'name': '临汾',
      'firstSpell': 'L',
      'shortSpell': 'LF',
      'spell': 'LinFen'
    }, {
      'regionId': '411100',
      'name': '漯河',
      'firstSpell': 'L',
      'shortSpell': 'LH',
      'spell': 'LuoHe'
    }, {
      'regionId': '530700',
      'name': '丽江',
      'firstSpell': 'L',
      'shortSpell': 'LJ',
      'spell': 'LiJiang'
    }, {
      'regionId': '141100',
      'name': '吕梁',
      'firstSpell': 'L',
      'shortSpell': 'LL',
      'spell': 'LvLiang'
    }, {
      'regionId': '621200',
      'name': '陇南',
      'firstSpell': 'L',
      'shortSpell': 'LN',
      'spell': 'LongNan'
    }, {
      'regionId': '520200',
      'name': '六盘水',
      'firstSpell': 'L',
      'shortSpell': 'LPS',
      'spell': 'LiuPanShui'
    }, {
      'regionId': '331100',
      'name': '丽水',
      'firstSpell': 'L',
      'shortSpell': 'LS',
      'spell': 'LiShui'
    }, {
      'regionId': '511100',
      'name': '乐山市',
      'firstSpell': 'L',
      'shortSpell': 'LS',
      'spell': 'LeShang'
    }, {
      'regionId': '513400',
      'name': '凉山',
      'firstSpell': 'L',
      'shortSpell': 'LS',
      'spell': 'LiangShan'
    }, {
      'regionId': '371200',
      'name': '莱芜',
      'firstSpell': 'L',
      'shortSpell': 'LW',
      'spell': 'LaiWu'
    }, {
      'regionId': '622900',
      'name': '临夏',
      'firstSpell': 'L',
      'shortSpell': 'LX',
      'spell': 'LinXia'
    }, {
      'regionId': '211000',
      'name': '辽阳',
      'firstSpell': 'L',
      'shortSpell': 'LY',
      'spell': 'LiaoYang'
    }, {
      'regionId': '220400',
      'name': '辽源',
      'firstSpell': 'L',
      'shortSpell': 'LY',
      'spell': 'LiaoYuan'
    }, {
      'regionId': '350800',
      'name': '龙岩',
      'firstSpell': 'L',
      'shortSpell': 'LY',
      'spell': 'LongYan'
    }, {
      'regionId': '371300',
      'name': '临沂',
      'firstSpell': 'L',
      'shortSpell': 'LY',
      'spell': 'LinYi'
    }, {
      'regionId': '410300',
      'name': '洛阳',
      'firstSpell': 'L',
      'shortSpell': 'LY',
      'spell': 'LuoYang'
    }, {
      'regionId': '320700',
      'name': '连云港',
      'firstSpell': 'L',
      'shortSpell': 'LYG',
      'spell': 'LianYunGang'
    }, {
      'regionId': '450200',
      'name': '柳州',
      'firstSpell': 'L',
      'shortSpell': 'LZ',
      'spell': 'LiuZhou'
    }, {
      'regionId': '510500',
      'name': '泸州',
      'firstSpell': 'L',
      'shortSpell': 'LZ',
      'spell': 'LuZhou'
    }, {
      'regionId': '542600',
      'name': '林芝',
      'firstSpell': 'L',
      'shortSpell': 'LZ',
      'spell': 'LinZhi'
    }],
    'M': [{
      'regionId': '340500',
      'name': '马鞍山',
      'firstSpell': 'M',
      'shortSpell': 'MAS',
      'spell': 'MaAnShan'
    }, {
      'regionId': '231000',
      'name': '牡丹江',
      'firstSpell': 'M',
      'shortSpell': 'MDJ',
      'spell': 'MuDanJiang'
    }, {
      'regionId': '440900',
      'name': '茂名',
      'firstSpell': 'M',
      'shortSpell': 'MM',
      'spell': 'MaoMing'
    }, {
      'regionId': '511400',
      'name': '眉山',
      'firstSpell': 'M',
      'shortSpell': 'MS',
      'spell': 'MeiShan'
    }, {
      'regionId': '510700',
      'name': '绵阳',
      'firstSpell': 'M',
      'shortSpell': 'MY',
      'spell': 'MianYang'
    }, {
      'regionId': '441400',
      'name': '梅州',
      'firstSpell': 'M',
      'shortSpell': 'MZ',
      'spell': 'MeiZhou'
    }],
    'N': [{
      'regionId': '330200',
      'name': '宁波',
      'firstSpell': 'N',
      'shortSpell': 'NB',
      'spell': 'NingBo'
    }, {
      'regionId': '360100',
      'name': '南昌',
      'firstSpell': 'N',
      'shortSpell': 'NC',
      'spell': 'NanChang'
    }, {
      'regionId': '320100',
      'name': '南京',
      'firstSpell': 'N',
      'shortSpell': 'NJ',
      'spell': 'NanJing'
    }, {
      'regionId': '450100',
      'name': '南宁',
      'firstSpell': 'N',
      'shortSpell': 'NN',
      'spell': 'NanNing'
    }, {
      'regionId': '511300',
      'name': '南充',
      'firstSpell': 'N',
      'shortSpell': 'NC',
      'spell': 'NanChong'
    }, {
      'regionId': '350900',
      'name': '宁德',
      'firstSpell': 'N',
      'shortSpell': 'ND',
      'spell': 'NingDe'
    }, {
      'regionId': '511000',
      'name': '内江',
      'firstSpell': 'N',
      'shortSpell': 'NJ',
      'spell': 'NeiJiang'
    }, {
      'regionId': '533300',
      'name': '怒江',
      'firstSpell': 'N',
      'shortSpell': 'NJ',
      'spell': 'NuJiang'
    }, {
      'regionId': '350700',
      'name': '南平',
      'firstSpell': 'N',
      'shortSpell': 'NP',
      'spell': 'NanPing'
    }, {
      'regionId': '542400',
      'name': '那曲',
      'firstSpell': 'N',
      'shortSpell': 'NQ',
      'spell': 'NaQu'
    }, {
      'regionId': '320600',
      'name': '南通',
      'firstSpell': 'N',
      'shortSpell': 'NT',
      'spell': 'NanTong'
    }, {
      'regionId': '411300',
      'name': '南阳',
      'firstSpell': 'N',
      'shortSpell': 'NY',
      'spell': 'NanYang'
    }],
    'P': [{
      'regionId': '410400',
      'name': '平顶山',
      'firstSpell': 'P',
      'shortSpell': 'PDS',
      'spell': 'PingDingShan'
    }, {
      'regionId': '530800',
      'name': '普洱',
      'firstSpell': 'P',
      'shortSpell': 'PE',
      'spell': 'PuEr'
    }, {
      'regionId': '211100',
      'name': '盘锦',
      'firstSpell': 'P',
      'shortSpell': 'PJ',
      'spell': 'PanJin'
    }, {
      'regionId': '620800',
      'name': '平凉',
      'firstSpell': 'P',
      'shortSpell': 'PL',
      'spell': 'PingLiang'
    }, {
      'regionId': '350300',
      'name': '莆田',
      'firstSpell': 'P',
      'shortSpell': 'PT',
      'spell': 'PuTian'
    }, {
      'regionId': '360300',
      'name': '萍乡',
      'firstSpell': 'P',
      'shortSpell': 'PX',
      'spell': 'PingXang'
    }, {
      'regionId': '410900',
      'name': '濮阳',
      'firstSpell': 'P',
      'shortSpell': 'PY',
      'spell': 'PuYang'
    }, {
      'regionId': '510400',
      'name': '攀枝花',
      'firstSpell': 'P',
      'shortSpell': 'PZH',
      'spell': 'PanZhiHua'
    }],
    'Q': [{
      'regionId': '370200',
      'name': '青岛',
      'firstSpell': 'Q',
      'shortSpell': 'QD',
      'spell': 'QingDao'
    }, {
      'regionId': '522600',
      'name': '黔东',
      'firstSpell': 'Q',
      'shortSpell': 'QD',
      'spell': 'QianDong'
    }, {
      'regionId': '469002',
      'name': '琼海',
      'firstSpell': 'Q',
      'shortSpell': 'QH',
      'spell': 'QiongHai'
    }, {
      'regionId': '130300',
      'name': '秦皇岛',
      'firstSpell': 'Q',
      'shortSpell': 'QHD',
      'spell': 'QinHuangDao'
    }, {
      'regionId': '429005',
      'name': '潜江',
      'firstSpell': 'Q',
      'shortSpell': 'QJ',
      'spell': 'QianJiang'
    }, {
      'regionId': '530300',
      'name': '曲靖',
      'firstSpell': 'Q',
      'shortSpell': 'QJ',
      'spell': 'QuJing'
    }, {
      'regionId': '522700',
      'name': '黔南',
      'firstSpell': 'Q',
      'shortSpell': 'QN',
      'spell': 'QianNan'
    }, {
      'regionId': '230200',
      'name': '齐齐哈尔',
      'firstSpell': 'Q',
      'shortSpell': 'QQHE',
      'spell': 'QiQiHaEr'
    }, {
      'regionId': '230900',
      'name': '七台河',
      'firstSpell': 'Q',
      'shortSpell': 'QTH',
      'spell': 'QiTaiHe'
    }, {
      'regionId': '522300',
      'name': '黔西',
      'firstSpell': 'Q',
      'shortSpell': 'QX',
      'spell': 'QianXi'
    }, {
      'regionId': '441800',
      'name': '清远',
      'firstSpell': 'Q',
      'shortSpell': 'QY',
      'spell': 'QingYuan'
    }, {
      'regionId': '621000',
      'name': '庆阳',
      'firstSpell': 'Q',
      'shortSpell': 'QY',
      'spell': 'QingYang'
    }, {
      'regionId': '330800',
      'name': '衢州',
      'firstSpell': 'Q',
      'shortSpell': 'QZ',
      'spell': 'QuZhou'
    }, {
      'regionId': '350500',
      'name': '泉州',
      'firstSpell': 'Q',
      'shortSpell': 'QZ',
      'spell': 'QuanZhou'
    }, {
      'regionId': '450700',
      'name': '钦州',
      'firstSpell': 'Q',
      'shortSpell': 'QZ',
      'spell': 'QinZhou'
    }],
    'R': [{
      'regionId': '540200',
      'name': '日喀则',
      'firstSpell': 'R',
      'shortSpell': 'RKZ',
      'spell': 'RiKaZe'
    }, {
      'regionId': '371100',
      'name': '日照',
      'firstSpell': 'R',
      'shortSpell': 'RZ',
      'spell': 'RiZhao'
    }],
    'S': [{
      'regionId': '310100',
      'name': '上海',
      'firstSpell': 'S',
      'shortSpell': 'SH',
      'spell': 'ShangHai'
    }, {
      'regionId': '440300',
      'name': '深圳',
      'firstSpell': 'S',
      'shortSpell': 'SZ',
      'spell': 'ShenZhen'
    }, {
      'regionId': '130100',
      'name': '石家庄',
      'firstSpell': 'S',
      'shortSpell': 'SJZ',
      'spell': 'ShiJiaZhuang'
    }, {
      'regionId': '210100',
      'name': '沈阳',
      'firstSpell': 'S',
      'shortSpell': 'SY',
      'spell': 'ShenYang'
    }, {
      'regionId': '440200',
      'name': '韶关',
      'firstSpell': 'S',
      'shortSpell': 'SG',
      'spell': 'ShaoGuan'
    }, {
      'regionId': '231200',
      'name': '绥化',
      'firstSpell': 'S',
      'shortSpell': 'SH',
      'spell': 'SuiHua'
    }, {
      'regionId': '659001',
      'name': '石河子',
      'firstSpell': 'S',
      'shortSpell': 'SHZ',
      'spell': 'ShiHeZi'
    }, {
      'regionId': '611000',
      'name': '商洛',
      'firstSpell': 'S',
      'shortSpell': 'SL',
      'spell': 'ShangLuo'
    }, {
      'regionId': '350400',
      'name': '三明',
      'firstSpell': 'S',
      'shortSpell': 'SM',
      'spell': 'SanMing'
    }, {
      'regionId': '411200',
      'name': '三门峡',
      'firstSpell': 'S',
      'shortSpell': 'SMX',
      'spell': 'SanMenXia'
    }, {
      'regionId': '429021',
      'name': '神农',
      'firstSpell': 'S',
      'shortSpell': 'SN',
      'spell': 'ShenNong'
    }, {
      'regionId': '510900',
      'name': '遂宁',
      'firstSpell': 'S',
      'shortSpell': 'SN',
      'spell': 'SuiNing'
    }, {
      'regionId': '542200',
      'name': '山南',
      'firstSpell': 'S',
      'shortSpell': 'SN',
      'spell': 'ShanNan'
    }, {
      'regionId': '220300',
      'name': '四平',
      'firstSpell': 'S',
      'shortSpell': 'SP',
      'spell': 'SiPing'
    }, {
      'regionId': '321300',
      'name': '宿迁',
      'firstSpell': 'S',
      'shortSpell': 'SQ',
      'spell': 'SuQian'
    }, {
      'regionId': '411400',
      'name': '商丘',
      'firstSpell': 'S',
      'shortSpell': 'SQ',
      'spell': 'ShangQiu'
    }, {
      'regionId': '361100',
      'name': '上饶',
      'firstSpell': 'S',
      'shortSpell': 'SR',
      'spell': 'ShangRao'
    }, {
      'regionId': '460300',
      'name': '三沙',
      'firstSpell': 'S',
      'shortSpell': 'SS',
      'spell': 'SanSha'
    }, {
      'regionId': '440500',
      'name': '汕头',
      'firstSpell': 'S',
      'shortSpell': 'ST',
      'spell': 'ShanTou'
    }, {
      'regionId': '441500',
      'name': '汕尾',
      'firstSpell': 'S',
      'shortSpell': 'SW',
      'spell': 'ShanWei'
    }, {
      'regionId': '330600',
      'name': '绍兴',
      'firstSpell': 'S',
      'shortSpell': 'SX',
      'spell': 'ShaoXing'
    }, {
      'regionId': '220700',
      'name': '松原',
      'firstSpell': 'S',
      'shortSpell': 'SY',
      'spell': 'SongYuan'
    }, {
      'regionId': '420300',
      'name': '十堰',
      'firstSpell': 'S',
      'shortSpell': 'SY',
      'spell': 'ShiYan'
    }, {
      'regionId': '430500',
      'name': '邵阳',
      'firstSpell': 'S',
      'shortSpell': 'SY',
      'spell': 'ShaoYang'
    }, {
      'regionId': '460200',
      'name': '三亚',
      'firstSpell': 'S',
      'shortSpell': 'SY',
      'spell': 'SanYa'
    }, {
      'regionId': '230500',
      'name': '双鸭山',
      'firstSpell': 'S',
      'shortSpell': 'SYS',
      'spell': 'ShuangYaShan'
    }, {
      'regionId': '140600',
      'name': '朔州',
      'firstSpell': 'S',
      'shortSpell': 'SZ',
      'spell': 'ShuoZhou'
    }, {
      'regionId': '320500',
      'name': '苏州',
      'firstSpell': 'S',
      'shortSpell': 'SZ',
      'spell': 'SuZhou'
    }, {
      'regionId': '341300',
      'name': '宿州',
      'firstSpell': 'S',
      'shortSpell': 'SZ',
      'spell': 'SuZhou'
    }, {
      'regionId': '421300',
      'name': '随州',
      'firstSpell': 'S',
      'shortSpell': 'SZ',
      'spell': 'SuiZhou'
    }, {
      'regionId': '640200',
      'name': '石嘴山',
      'firstSpell': 'S',
      'shortSpell': 'SZS',
      'spell': 'ShiZuiShan'
    }],
    'T': [{
      'regionId': '120100',
      'name': '天津',
      'firstSpell': 'T',
      'shortSpell': 'TJ',
      'spell': 'TianJin'
    }, {
      'regionId': '140100',
      'name': '太原',
      'firstSpell': 'T',
      'shortSpell': 'TY',
      'spell': 'TaiYuan'
    }, {
      'regionId': '370900',
      'name': '泰安',
      'firstSpell': 'T',
      'shortSpell': 'TA',
      'spell': 'TaiAn'
    }, {
      'regionId': '610200',
      'name': '铜川',
      'firstSpell': 'T',
      'shortSpell': 'TC',
      'spell': 'TongChuan'
    }, {
      'regionId': '654200',
      'name': '塔城',
      'firstSpell': 'T',
      'shortSpell': 'TC',
      'spell': 'TaCheng'
    }, {
      'regionId': '220500',
      'name': '通化',
      'firstSpell': 'T',
      'shortSpell': 'TH',
      'spell': 'TongHua'
    }, {
      'regionId': '150500',
      'name': '通辽',
      'firstSpell': 'T',
      'shortSpell': 'TL',
      'spell': 'TongLiao'
    }, {
      'regionId': '211200',
      'name': '铁岭',
      'firstSpell': 'T',
      'shortSpell': 'TL',
      'spell': 'TieLing'
    }, {
      'regionId': '340700',
      'name': '铜陵',
      'firstSpell': 'T',
      'shortSpell': 'TL',
      'spell': 'TongLing'
    }, {
      'regionId': '652100',
      'name': '吐鲁番',
      'firstSpell': 'T',
      'shortSpell': 'TLF',
      'spell': 'TuLuFan'
    }, {
      'regionId': '429006',
      'name': '天门',
      'firstSpell': 'T',
      'shortSpell': 'TM',
      'spell': 'TianMen'
    }, {
      'regionId': '659003',
      'name': '图木舒克',
      'firstSpell': 'T',
      'shortSpell': 'TMSK',
      'spell': 'TuMuShuKe'
    }, {
      'regionId': '520600',
      'name': '铜仁',
      'firstSpell': 'T',
      'shortSpell': 'TR',
      'spell': 'TongRen'
    }, {
      'regionId': '130200',
      'name': '唐山',
      'firstSpell': 'T',
      'shortSpell': 'TS',
      'spell': 'TangShan'
    }, {
      'regionId': '620500',
      'name': '天水',
      'firstSpell': 'T',
      'shortSpell': 'TS',
      'spell': 'TianShui'
    }, {
      'regionId': '321200',
      'name': '泰州',
      'firstSpell': 'T',
      'shortSpell': 'TZ',
      'spell': 'TaiZhou'
    }, {
      'regionId': '331000',
      'name': '台州',
      'firstSpell': 'T',
      'shortSpell': 'TZ',
      'spell': 'TaiZhou'
    }],
    'W': [{
      'regionId': '420100',
      'name': '武汉',
      'firstSpell': 'W',
      'shortSpell': 'WH',
      'spell': 'WuHan'
    }, {
      'regionId': '650100',
      'name': '乌鲁木齐',
      'firstSpell': 'W',
      'shortSpell': 'WLMQ',
      'spell': 'WuLuMuQi'
    }, {
      'regionId': '469005',
      'name': '文昌',
      'firstSpell': 'W',
      'shortSpell': 'WC',
      'spell': 'WenChang'
    }, {
      'regionId': '370700',
      'name': '潍坊',
      'firstSpell': 'W',
      'shortSpell': 'WF',
      'spell': 'WeiFang'
    }, {
      'regionId': '150300',
      'name': '乌海',
      'firstSpell': 'W',
      'shortSpell': 'WH',
      'spell': 'WuHai'
    }, {
      'regionId': '340200',
      'name': '芜湖',
      'firstSpell': 'W',
      'shortSpell': 'WH',
      'spell': 'WuHu'
    }, {
      'regionId': '371000',
      'name': '威海',
      'firstSpell': 'W',
      'shortSpell': 'WH',
      'spell': 'WeiHai'
    }, {
      'regionId': '659004',
      'name': '五家渠',
      'firstSpell': 'W',
      'shortSpell': 'WJQ',
      'spell': 'WuJiaQu'
    }, {
      'regionId': '150900',
      'name': '乌兰察布',
      'firstSpell': 'W',
      'shortSpell': 'WLCB',
      'spell': 'WuLanChaBu'
    }, {
      'regionId': '469006',
      'name': '万宁',
      'firstSpell': 'W',
      'shortSpell': 'WN',
      'spell': 'WanNing'
    }, {
      'regionId': '610500',
      'name': '渭南',
      'firstSpell': 'W',
      'shortSpell': 'WN',
      'spell': 'WeiNan'
    }, {
      'regionId': '532600',
      'name': '文山',
      'firstSpell': 'W',
      'shortSpell': 'WS',
      'spell': 'WenShang'
    }, {
      'regionId': '620600',
      'name': '武威',
      'firstSpell': 'W',
      'shortSpell': 'WW',
      'spell': 'WuWei'
    }, {
      'regionId': '320200',
      'name': '无锡',
      'firstSpell': 'W',
      'shortSpell': 'WX',
      'spell': 'WuXi'
    }, {
      'regionId': '330300',
      'name': '温州',
      'firstSpell': 'W',
      'shortSpell': 'WZ',
      'spell': 'WenZhou'
    }, {
      'regionId': '450400',
      'name': '梧州',
      'firstSpell': 'W',
      'shortSpell': 'WZ',
      'spell': 'WuZhou'
    }, {
      'regionId': '640300',
      'name': '吴忠',
      'firstSpell': 'W',
      'shortSpell': 'WZ',
      'spell': 'WuZhong'
    }, {
      'regionId': '469001',
      'name': '五指山',
      'firstSpell': 'W',
      'shortSpell': 'WZS',
      'spell': 'WuZhiShan'
    }],
    'X': [{
      'regionId': '350200',
      'name': '厦门',
      'firstSpell': 'X',
      'shortSpell': 'XM',
      'spell': 'XiaMen'
    }, {
      'regionId': '610100',
      'name': '西安',
      'firstSpell': 'X',
      'shortSpell': 'XA',
      'spell': 'XiAn'
    }, {
      'regionId': '630100',
      'name': '西宁',
      'firstSpell': 'X',
      'shortSpell': 'XN',
      'spell': 'XiNing'
    }, {
      'regionId': '152200',
      'name': '兴安盟',
      'firstSpell': 'X',
      'shortSpell': 'XAM',
      'spell': 'XingAnMeng'
    }, {
      'regionId': '341800',
      'name': '宣城',
      'firstSpell': 'X',
      'shortSpell': 'XC',
      'spell': 'XuanCheng'
    }, {
      'regionId': '411000',
      'name': '许昌',
      'firstSpell': 'X',
      'shortSpell': 'XC',
      'spell': 'XuChang'
    }, {
      'regionId': '420600',
      'name': '襄樊',
      'firstSpell': 'X',
      'shortSpell': 'XF',
      'spell': 'XiangFan'
    }, {
      'regionId': '420900',
      'name': '孝感',
      'firstSpell': 'X',
      'shortSpell': 'XG',
      'spell': 'XiaoGan'
    }, {
      'regionId': '152500',
      'name': '锡林郭勒',
      'firstSpell': 'X',
      'shortSpell': 'XLGLM',
      'spell': 'XiLinGuoLeMeng'
    }, {
      'regionId': '421200',
      'name': '咸宁',
      'firstSpell': 'X',
      'shortSpell': 'XN',
      'spell': 'XianNing'
    }, {
      'regionId': '532800',
      'name': '西双版纳',
      'firstSpell': 'X',
      'shortSpell': 'XSBN',
      'spell': 'XiShuangBanNa'
    }, {
      'regionId': '130500',
      'name': '邢台',
      'firstSpell': 'X',
      'shortSpell': 'XT',
      'spell': 'XingTai'
    }, {
      'regionId': '429004',
      'name': '仙桃',
      'firstSpell': 'X',
      'shortSpell': 'XT',
      'spell': 'XianTao'
    }, {
      'regionId': '430300',
      'name': '湘潭',
      'firstSpell': 'X',
      'shortSpell': 'XT',
      'spell': 'XiangTan'
    }, {
      'regionId': '410700',
      'name': '新乡',
      'firstSpell': 'X',
      'shortSpell': 'XX',
      'spell': 'XinXiang'
    }, {
      'regionId': '433100',
      'name': '湘西',
      'firstSpell': 'X',
      'shortSpell': 'XX',
      'spell': 'XiangXi'
    }, {
      'regionId': '360500',
      'name': '新余',
      'firstSpell': 'X',
      'shortSpell': 'XY',
      'spell': 'XinYu'
    }, {
      'regionId': '411500',
      'name': '信阳',
      'firstSpell': 'X',
      'shortSpell': 'XY',
      'spell': 'XinYang'
    }, {
      'regionId': '610400',
      'name': '咸阳',
      'firstSpell': 'X',
      'shortSpell': 'XY',
      'spell': 'XianYang'
    }, {
      'regionId': '140900',
      'name': '忻州',
      'firstSpell': 'X',
      'shortSpell': 'XZ',
      'spell': 'XinZhou'
    }, {
      'regionId': '320300',
      'name': '徐州',
      'firstSpell': 'X',
      'shortSpell': 'XZ',
      'spell': 'XuZhou'
    }],
    'Y': [{
      'regionId': '654002',
      'name': '伊宁市',
      'firstSpell': 'Y',
      'shortSpell': 'YN',
      'spell': 'YiNing'
    }, {
      'regionId': '640100',
      'name': '银川',
      'firstSpell': 'Y',
      'shortSpell': 'YC',
      'spell': 'YinChuan'
    }, {
      'regionId': '511800',
      'name': '雅安',
      'firstSpell': 'Y',
      'shortSpell': 'YA',
      'spell': 'YaAn'
    }, {
      'regionId': '610600',
      'name': '延安',
      'firstSpell': 'Y',
      'shortSpell': 'YA',
      'spell': 'YanAn'
    }, {
      'regionId': '222400',
      'name': '延边',
      'firstSpell': 'Y',
      'shortSpell': 'YB',
      'spell': 'YanBian'
    }, {
      'regionId': '511500',
      'name': '宜宾',
      'firstSpell': 'Y',
      'shortSpell': 'YB',
      'spell': 'YiBin'
    }, {
      'regionId': '140800',
      'name': '运城',
      'firstSpell': 'Y',
      'shortSpell': 'YC',
      'spell': 'YunCheng'
    }, {
      'regionId': '230700',
      'name': '伊春',
      'firstSpell': 'Y',
      'shortSpell': 'YC',
      'spell': 'YiChun'
    }, {
      'regionId': '320900',
      'name': '盐城',
      'firstSpell': 'Y',
      'shortSpell': 'YC',
      'spell': 'YanCheng'
    }, {
      'regionId': '360900',
      'name': '宜春',
      'firstSpell': 'Y',
      'shortSpell': 'YC',
      'spell': 'YiChun'
    }, {
      'regionId': '420500',
      'name': '宜昌',
      'firstSpell': 'Y',
      'shortSpell': 'YC',
      'spell': 'YiChang'
    }, {
      'regionId': '445300',
      'name': '云浮',
      'firstSpell': 'Y',
      'shortSpell': 'YF',
      'spell': 'YunFu'
    }, {
      'regionId': '441700',
      'name': '阳江',
      'firstSpell': 'Y',
      'shortSpell': 'YJ',
      'spell': 'YangJiang'
    }, {
      'regionId': '210800',
      'name': '营口',
      'firstSpell': 'Y',
      'shortSpell': 'YK',
      'spell': 'YingKou'
    }, {
      'regionId': '450900',
      'name': '玉林',
      'firstSpell': 'Y',
      'shortSpell': 'YL',
      'spell': 'YuLin'
    }, {
      'regionId': '610800',
      'name': '榆林',
      'firstSpell': 'Y',
      'shortSpell': 'YL',
      'spell': 'YuLin'
    }, {
      'regionId': '654000',
      'name': '伊犁',
      'firstSpell': 'Y',
      'shortSpell': 'YL',
      'spell': 'YiLi'
    }, {
      'regionId': '140300',
      'name': '阳泉',
      'firstSpell': 'Y',
      'shortSpell': 'YQ',
      'spell': 'YangQuan'
    }, {
      'regionId': '632700',
      'name': '玉树',
      'firstSpell': 'Y',
      'shortSpell': 'YS',
      'spell': 'YuShu'
    }, {
      'regionId': '360600',
      'name': '鹰潭',
      'firstSpell': 'Y',
      'shortSpell': 'YT',
      'spell': 'YingTan'
    }, {
      'regionId': '370600',
      'name': '烟台',
      'firstSpell': 'Y',
      'shortSpell': 'YT',
      'spell': 'YanTai'
    }, {
      'regionId': '530400',
      'name': '玉溪',
      'firstSpell': 'Y',
      'shortSpell': 'YX',
      'spell': 'YuXi'
    }, {
      'regionId': '430600',
      'name': '岳阳',
      'firstSpell': 'Y',
      'shortSpell': 'YY',
      'spell': 'YueYang'
    }, {
      'regionId': '430900',
      'name': '益阳',
      'firstSpell': 'Y',
      'shortSpell': 'YY',
      'spell': 'YiYang'
    }, {
      'regionId': '321000',
      'name': '扬州',
      'firstSpell': 'Y',
      'shortSpell': 'YZ',
      'spell': 'YangZhou'
    }, {
      'regionId': '431100',
      'name': '永州',
      'firstSpell': 'Y',
      'shortSpell': 'YZ',
      'spell': 'YongZhou'
    }],
    'Z': [{
      'regionId': '410100',
      'name': '郑州',
      'firstSpell': 'Z',
      'shortSpell': 'ZZ',
      'spell': 'ZhengZhou'
    }, {
      'regionId': '370300',
      'name': '淄博',
      'firstSpell': 'Z',
      'shortSpell': 'ZB',
      'spell': 'ZiBo'
    }, {
      'regionId': '510300',
      'name': '自贡',
      'firstSpell': 'Z',
      'shortSpell': 'ZG',
      'spell': 'ZiGong'
    }, {
      'regionId': '440400',
      'name': '珠海',
      'firstSpell': 'Z',
      'shortSpell': 'ZH',
      'spell': 'ZhuHai'
    }, {
      'regionId': '321100',
      'name': '镇江',
      'firstSpell': 'Z',
      'shortSpell': 'ZJ',
      'spell': 'ZhenJiang'
    }, {
      'regionId': '440800',
      'name': '湛江',
      'firstSpell': 'Z',
      'shortSpell': 'ZJ',
      'spell': 'ZhanJiang'
    }, {
      'regionId': '430800',
      'name': '张家界',
      'firstSpell': 'Z',
      'shortSpell': 'ZJJ',
      'spell': 'ZhangJiaJie'
    }, {
      'regionId': '130700',
      'name': '张家口',
      'firstSpell': 'Z',
      'shortSpell': 'ZJK',
      'spell': 'ZhangJiaKou'
    }, {
      'regionId': '411600',
      'name': '周口',
      'firstSpell': 'Z',
      'shortSpell': 'ZK',
      'spell': 'ZhouKou'
    }, {
      'regionId': '411700',
      'name': '驻马店',
      'firstSpell': 'Z',
      'shortSpell': 'ZMD',
      'spell': 'ZhuMaDian'
    }, {
      'regionId': '441200',
      'name': '肇庆',
      'firstSpell': 'Z',
      'shortSpell': 'ZQ',
      'spell': 'ZhaoQing'
    }, {
      'regionId': '330900',
      'name': '舟山',
      'firstSpell': 'Z',
      'shortSpell': 'ZS',
      'spell': 'ZhouShan'
    }, {
      'regionId': '442000',
      'name': '中山',
      'firstSpell': 'Z',
      'shortSpell': 'ZS',
      'spell': 'ZhongShan'
    }, {
      'regionId': '530600',
      'name': '昭通',
      'firstSpell': 'Z',
      'shortSpell': 'ZT',
      'spell': 'ZhaoTong'
    }, {
      'regionId': '640500',
      'name': '中卫',
      'firstSpell': 'Z',
      'shortSpell': 'ZW',
      'spell': 'ZhongWei'
    }, {
      'regionId': '512000',
      'name': '资阳',
      'firstSpell': 'Z',
      'shortSpell': 'ZY',
      'spell': 'ZiYang'
    }, {
      'regionId': '520300',
      'name': '遵义',
      'firstSpell': 'Z',
      'shortSpell': 'ZY',
      'spell': 'ZunYi'
    }, {
      'regionId': '620700',
      'name': '张掖',
      'firstSpell': 'Z',
      'shortSpell': 'ZY',
      'spell': 'ZhangYe'
    }, {
      'regionId': '350600',
      'name': '漳州',
      'firstSpell': 'Z',
      'shortSpell': 'ZZ',
      'spell': 'ZhangZhou'
    }, {
      'regionId': '370400',
      'name': '枣庄',
      'firstSpell': 'Z',
      'shortSpell': 'ZZ',
      'spell': 'ZaoZhuang'
    }, {
      'regionId': '430200',
      'name': '株洲',
      'firstSpell': 'Z',
      'shortSpell': 'ZZ',
      'spell': 'ZhuZhou'
    }]
  }
]

const cityInfo = {
  hotCity: hotCity,
  cityList: citys
}
export default cityInfo
